# Generated by Django 4.0.4 on 2022-05-03 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('order', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Sku')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('price', models.FloatField(verbose_name='Price')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('order_by', models.SmallIntegerField(default=0, verbose_name='Order')),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zebrands.brand')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['order_by', 'is_active', 'name', 'brand_id'],
            },
        ),
        migrations.CreateModel(
            name='TrackProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='User')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zebrands.product')),
            ],
        ),
    ]
